version: 2
updates:
  # update GitHub actions versions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "01:00"
    commit-message:
      prefix: "[MNT] "
    labels:
      - "maintenance"
      - "dependencies"
      - "no changelog"
    groups:
      github-actions:
        patterns:
          - "*"
  # update Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "01:00"
    commit-message:
      prefix: "[MNT] "
    labels:
      - "maintenance"
      - "dependencies"
      - "full pytest actions"
      - "no changelog"
    groups:
      python-packages:
        patterns:
          - "*"
