anomaly detection:
- "aeon/anomaly_detection/**"

benchmarking:
- "aeon/benchmarking/**"

classification:
- "aeon/classification/**"

clustering:
- "aeon/clustering/**"

datasets:
- "aeon/datasets/**"

datatypes:
- "aeon/datatypes/**"

distances:
- "aeon/distances/**"

examples:
- "examples/**"

forecasting:
- "aeon/forecasting/**"

networks:
- "aeon/networks/**"

regression:
- "aeon/regression/**"

segmentation:
- "aeon/segmentation/**"

similarity search:
- "aeon/similarity_search/**"

transformations:
- "aeon/transformations/**"
