changelog:
  categories:
    - title: '🚀 Features'
      labels:
        - 'enhancement'
        - 'implementing algorithms'
        - 'implementing framework'
        - 'interfacing algorithms'
    - title: '🐛 Bug Fixes'
      labels:
        - 'bug'
    - title: '🧰 Maintenance'
      label:
        - 'maintenance'
        - 'refactor'
        - 'testing'
    - title: '📖 Documentation'
      label:
        - 'documentation'
    - title: Other Changes
      labels:
        - "*"
