# PR status check
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        # If true PRs will always pass and reports are just for information
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        # If true PRs will always pass and reports are just for information
        informational: true

# post coverage report as comment on PR
comment: false

# enable codecov to report to GitHub status checks
github_checks:
  annotations: false

# paths to ignore
ignore:
  - ".github/"
  - ".binder/"
  - "aeon/testing/expected_results/results_reproduction/"
  - "docs/"
  - "examples/"
  - "datasets/_data_loaders.py"
