"""Script for handling AI Spam label on pull requests."""

import json
import os

from github import Github

context_dict = json.loads(os.getenv("CONTEXT_GITHUB"))

repo = context_dict["repository"]
g = Github(os.getenv("GITHUB_TOKEN"))
repo = g.get_repo(repo)
pr_number = context_dict["event"]["number"]
pr = repo.get_pull(number=pr_number)
labels = [label.name for label in pr.get_labels()]

if "AI pull request" in labels:
    pr.create_issue_comment(
        "This pull request has been flagged with the **AI pull request** label as it"
        "is suspected to be comprised of AI code and/or breaks our guidelines.\n\n"
        "`aeon` does not accept pull requests that are primarily generated by AI "
        "tools. Please read through our guidelines.\n\n"
        "If you believe this label has been applied in error, contact us on Discord or"
        "GitHub."
    )
    pr.edit(state="closed")
