name: ✨ Feature request
description: Suggest a new algorithm or idea for aeon.
title: "[ENH] "
labels: ["enhancement"]

body:
- type: textarea
  attributes:
    label: Describe the feature or idea you want to propose
    description: >
      Is your feature request related to a problem? Please describe. If it is a new estimator, you should link to the paper or other reference.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe your proposed solution
    description: >
      A clear and concise description of what you want to happen, ideally taking into consideration the existing toolbox design, classes and methods.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered, if relevant
    description: >
      A clear and concise description of any alternative solutions or features you've considered.
- type: textarea
  attributes:
    label: Additional context
    description: >
      Add any other context about the problem here.
