"""Configuration file for the Sphinx documentation builder."""

import importlib
import os
import sys
from pathlib import Path

from sphinx.ext.autosummary import Autosummary

import aeon

# -- Project information -----------------------------------------------------

project = "aeon"
copyright = "The aeon developers (BSD-3 License)"
author = "aeon developers"

version = aeon.__version__
release = aeon.__version__

github_tag = f"v{version}"

# -- Path setup --------------------------------------------------------------

# local sphinx extensions
sys.path.append(str(Path(__file__).parent / "_sphinxext"))

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here.
on_readthedocs = os.environ.get("READTHEDOCS") == "True"
if not on_readthedocs:
    sys.path.insert(0, os.path.abspath(""))
else:
    rtd_version = os.environ.get("READTHEDOCS_VERSION")
    if rtd_version == "latest":
        github_tag = "main"

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "numpydoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.intersphinx",
    "sphinx.ext.linkcode",
    "sphinxext.opengraph",
    "nbsphinx",
    "sphinx_design",
    "sphinx_issues",
    "sphinx_copybutton",
    "versionwarning.extension",
    "myst_parser",
    # local extensions (_sphinxext/)
    "sphinx_remove_toctrees",
    "aeon_mini_gallery",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# The main toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    "_build",
    ".ipynb_checkpoints",
    "Thumbs.db",
    ".DS_Store",
]

# A boolean that decides whether module names are prepended to all object names (for
# object types where a “module” of some kind is defined), e.g. for py:function
# directives.
add_module_names = False

# -- Extension configuration -------------------------------------------------

# -- numpydoc --

# see http://stackoverflow.com/q/12206334/562769
#     https://github.com/numpy/numpydoc/issues/69
# Lots of warnings
numpydoc_show_class_members = True

# Whether to create a Sphinx table of contents for the lists of class methods and
# attributes. If a table of contents is made, Sphinx expects each entry to have a
# separate page.
# We remove the toctree for API for speed and do not want separate pages for this
numpydoc_class_members_toctree = False

# Whether to produce plot:: directives for Examples sections that contain
# 'import matplotlib' or 'from matplotlib import'.
numpydoc_use_plots = True

# Options for the ::plot directive:
# https://matplotlib.org/stable/api/sphinxext_plot_directive_api.html
plot_formats = ["png"]
plot_include_source = True
plot_html_show_formats = False
plot_html_show_source_link = False

# This will produce warnings for docstring errors.
numpydoc_validation_checks = {
    "all",
    "GL01",  # docstring starts after opening quotes
    "ES01",  # no extended summary
    "SA01",  # no see also section
    "EX01",  # no examples
}

# If true, '()' will be appended to :func: etc. cross-reference text.
add_function_parentheses = False

# -- autosummary and autodoc --

# generate autosummary even if no references
autosummary_generate = True

# Members and inherited-members default to showing methods and attributes from a
# class or those inherited.
# Member-order orders the documentation in the order of how the members are defined in
# the source code.
autodoc_default_options = {
    "class-doc-from": "class",
    "members": True,
    "exclude-members": "get_metadata_routing, set_output",
    "inherited-members": True,
    "show-inheritance": True,
}

# show "fit" instead of "RocketClassifier.fit" in the page table of contents
toc_object_entries_show_parents = "hide"

# -- autosectionlabel --

autosectionlabel_maxdepth = 4

# -- intersphinx --

intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
    "matplotlib": ("https://matplotlib.org/stable/", None),
    "pandas": ("https://pandas.pydata.org/pandas-docs/stable/", None),
    "joblib": ("https://joblib.readthedocs.io/en/latest/", None),
    "scikit-learn": ("https://scikit-learn.org/stable/", None),
}

# -- nbsphinx --

nbsphinx_execute = "never"  # whether to run notebooks
nbsphinx_allow_errors = False
nbsphinx_timeout = 600  # seconds, set to -1 to disable timeout

# RequireJS is only needed for notebook widgets, which we do not use. The theme loads
# scripts in the page head, so RequireJS would run before the DataTables script of the
# estimator overview and stop it from registering as a jQuery plugin.
nbsphinx_requirejs_path = ""

# Binder launch button
current_file = "{{ env.doc2path( env.docname, base=None) }}"
binder_url = (
    f"https://mybinder.org/v2/gh/aeon-toolkit/aeon/{github_tag}?filepath={current_file}"
)

# link to original notebook
notebook_url = f"https://github.com/aeon-toolkit/aeon/tree/{github_tag}/{current_file}"

# add to the bottom of each notebook page
nbsphinx_epilog = f"""
----

Generated using nbsphinx_. The Jupyter notebook can be found here_.

|Binder|_

.. _here: {notebook_url}
.. _nbsphinx: https://nbsphinx.readthedocs.io/
.. |binder| image:: https://mybinder.org/badge_logo.svg
.. _Binder: {binder_url}
"""

# -- sphinx_issues --

issues_github_path = "aeon-toolkit/aeon"

# -- sphinx_copybutton --

copybutton_exclude = ".linenos, .gp, .go"

# -- MyST parser --

# "colon_fence" and "html_image" recommended by sphinx_design when using the MyST Parser
myst_enable_extensions = ["colon_fence", "html_image", "attrs_inline"]

myst_heading_anchors = 4

# --  sphinx-remove-toctrees --

# see https://github.com/pradyunsg/furo/pull/674
# we use an in-built alternative currently due to a bug. See sphinx_remove_toctrees.py
# extension issue https://github.com/executablebooks/sphinx-remove-toctrees/issues/9
remove_from_toctrees = [
    "api_reference/auto_generated/*",  # including all api pages significantly slows
    # down the documentation build
]

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML.
html_theme = "pydata_sphinx_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.

# The version switcher only lists the Read the Docs "stable" and "latest" aliases, so
# it does not need updating on release. The theme resolves relative paths against the
# site root, so the hosted documentation must use the absolute URL.
if on_readthedocs:
    switcher_json_url = "https://www.aeon-toolkit.org/en/latest/_static/switcher.json"
else:
    switcher_json_url = "_static/switcher.json"

html_theme_options = {
    "logo": {"alt_text": "aeon - Home"},
    "navbar_align": "left",
    "navbar_end": ["version-switcher", "theme-switcher", "navbar-icon-links"],
    "header_links_before_dropdown": 5,
    "switcher": {
        "json_url": switcher_json_url,
        "version_match": os.environ.get("READTHEDOCS_VERSION", "latest"),
    },
    "use_edit_page_button": True,
    "secondary_sidebar_items": ["page-toc", "edit-this-page"],
    "show_toc_level": 2,
    # keep the full URL of the code repositories cited in docstring references
    "shorten_urls": False,
    "footer_start": ["copyright"],
    "footer_end": ["sphinx-version", "theme-version"],
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/aeon-toolkit/aeon",
            "icon": "fa-brands fa-github",
        },
        {
            "name": "Discord",
            "url": "https://discord.gg/D6rzqHGKRJ",
            "icon": "fa-brands fa-discord",
        },
    ],
}

# used by the "edit this page" button
html_context = {
    "github_user": "aeon-toolkit",
    "github_repo": "aeon",
    "github_version": "main",
    "doc_path": "docs",
}

# these pages have no section navigation to show
html_sidebars = {
    "index": [],
    "installation": [],
    "getting_started": [],
    "estimator_overview": [],
    "changelog": [],
}

# logos
html_logo = "images/logo/aeon-logo-blue-2-compact.png"
html_favicon = "images/logo/aeon-favicon.ico"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = [
    "css/custom.css",
]

html_show_sourcelink = False

# -- Documentation functions and setup ---------------------------------------


def linkcode_resolve(domain, info):
    """Return URL to source code corresponding.

    Parameters
    ----------
    domain : str
    info : dict

    Returns
    -------
    url : str
    """

    def find_source():
        # try to find the file and line number, based on code from numpy:
        # https://github.com/numpy/numpy/blob/main/doc/source/conf.py#L286

        import inspect
        import os

        # Get the top-level object from the module name
        obj = sys.modules[info["module"]]

        # Traverse dotted path (e.g., module.submodule.Class.method)
        for part in info["fullname"].split("."):
            obj = getattr(obj, part)

        # Unwrapping decorators (if any), so we can get the true
        # source function
        if inspect.isfunction(obj):
            obj = inspect.unwrap(obj)

        # Get the source filename
        try:
            fn = inspect.getsourcefile(obj)
        except TypeError:
            fn = None

        # If no source file is found, return None (no link)
        if not fn:
            return None

        # Make filename relative to the aeon source directory
        startdir = Path(aeon.__file__).parent.parent
        try:
            fn = os.path.relpath(fn, start=startdir).replace(os.path.sep, "/")
        except ValueError:
            return None

        # Filter out files not in the aeon package
        # (e.g., inherited from sklearn)
        if not fn.startswith("aeon/"):
            return None

        # Get line range of the object
        source, lineno = inspect.getsourcelines(obj)
        return fn, lineno, lineno + len(source) - 1

    if domain != "py" or not info["module"]:
        return None
    try:
        result = find_source()
        if not result:
            return None
        filename = "%s#L%d-L%d" % result
    except Exception:
        filename = info["module"].replace(".", "/") + ".py"
    return "https://github.com/aeon-toolkit/aeon/blob/{}/{}".format(
        github_tag,
        filename,
    )


def _get_estimator_doc_path(estimator_class, estimator_name):
    """
    Get the documentation path for an estimator.

    Checks if the estimator is re-exported in a parent package's __all__.
    If found, uses the shorter public API path. Otherwise, falls back to
    the current underscore-filtering logic.

    Parameters
    ----------
    estimator_class : class
        The estimator class object
    estimator_name : str
        Name of the estimator

    Returns
    -------
    str
        The path to use for documentation links
        (e.g., 'aeon.classification.DummyClassifier')
    """
    module_path = estimator_class.__module__
    module_parts = module_path.split(".")

    # Check parent packages (skip the immediate module itself)
    # Start from len-1 to avoid checking the module containing the class
    for i in range(len(module_parts) - 1, 1, -1):
        parent_path = ".".join(module_parts[:i])
        try:
            parent_module = importlib.import_module(parent_path)

            # Check if exported in parent's __all__
            if (
                hasattr(parent_module, "__all__")
                and estimator_name in parent_module.__all__
            ):
                # Verify it's the same class
                if (
                    hasattr(parent_module, estimator_name)
                    and getattr(parent_module, estimator_name) is estimator_class
                ):
                    return f"{parent_path}.{estimator_name}"
        except (ImportError, AttributeError):
            continue

    modpath = str(estimator_class)[8:-2]
    path_parts = modpath.split(".")
    clean_path = ".".join([p for p in path_parts if not p.startswith("_")])
    return clean_path


def _make_estimator_overview(app):
    """Make estimator overview table."""
    import pandas as pd

    from aeon.utils.discovery import all_estimators

    def _does_not_start_with_underscore(input_string):
        return not input_string.startswith("_")

    # Columns for the output table
    base_columns = ["Estimator name", "Module", "Method family"]

    capabilities_to_include = {
        "multivariate": "Mult.",
        "unequal_length": "Uneq.",
        "missing_values": "Miss.",
    }

    # Initialize data dictionary with base columns
    data = {col: [] for col in base_columns}
    # Add abbreviated columns
    data.update({abbreviation: [] for abbreviation in capabilities_to_include.values()})

    for estimator_name, estimator_class in all_estimators(include_sklearn=False):
        algorithm_type = "::".join(str(estimator_class).split(".")[1:-2])
        # fetch tags
        tag_dict = estimator_class.get_class_tags()

        # Get documentation path using function that handles public API exports
        clean_path = _get_estimator_doc_path(estimator_class, estimator_name)
        # adds html link reference
        estimator_name_as_link = str(
            '<a href="api_reference/auto_generated/'
            + clean_path
            + '.html">'
            + estimator_name
            + "</a>"
        )
        algorithm_type = algorithm_type.split("::")
        data["Estimator name"].append(estimator_name_as_link)
        data["Module"].append(algorithm_type[0])
        if len(algorithm_type) > 1:
            data["Method family"].append("/".join(algorithm_type[1:]))
        else:
            data["Method family"].append("N/A")
        for capability_name, abbreviation in capabilities_to_include.items():
            _val = tag_dict.get(f"capability:{capability_name}")

            # For case where tag is not included output as not supported
            if not _val or _val is None:
                data[abbreviation].append("\u274c")
            else:
                data[abbreviation].append("\u2705")

    df = pd.DataFrame(data).sort_values(
        by=["Module", "Method family", "Estimator name"]
    )

    df_str = """
<!-- DataTables CSS -->
<link rel="stylesheet" type="text/css"
href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css">

<style>
.dataTables_wrapper {
    padding: 10px 0;
}

.dataTables_wrapper table.dataTable tbody tr {
    background-color: var(--pst-color-background);
    color: var(--pst-color-text-base);
}

.dataTables_wrapper table.dataTable tbody tr.odd {
    background-color: var(--pst-color-surface);
}

.dataTables_wrapper table.dataTable tbody tr:hover {
    background-color: var(--pst-color-on-background);
}

.dataTables_wrapper table.dataTable a {
    color: var(--pst-color-link);
}

.dataTables_length select {
    background-color: var(--pst-color-background) !important;
    color: var(--pst-color-text-base) !important;
    border: 1px solid var(--pst-color-border) !important;
}

.dataTables_length select option {
    background-color: var(--pst-color-background);
    color: var(--pst-color-text-base);
}

.dataTables_length select option:checked {
    background-color: var(--pst-color-on-background);
    color: var(--pst-color-text-base);
}

.dataTables_length select:focus {
    outline-color: var(--pst-color-border);
}
</style>
"""

    df_str += df.to_markdown(index=False, tablefmt="github")

    df_str += """
<!-- DataTables JS -->
<script type="text/javascript"
 src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
<script type="text/javascript"
 src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>

<script>
$(document).ready(function() {
    $('table').DataTable({
        pageLength: 10,
        order: [[1, 'asc'], [2, 'asc'], [0, 'asc']],
        language: {
            search: 'Search:',
            lengthMenu: 'Show _MENU_ entries'
        }
    });
});
</script>
"""

    with open("estimator_overview_table.md", "w", encoding="utf-8") as file:
        file.write(df_str)


def _add_estimator_capabilities_table(app, pagename, templatename, context, doctree):
    """Add estimator capabilities table to HTML page."""
    if "title" not in context or "body" not in context:
        return

    if '<span class="caption-text">Capabilities</span>' in context["body"]:
        return

    from aeon.utils.discovery import all_estimators

    estimators = all_estimators(include_sklearn=False)

    for estimator_name, estimator_class in estimators:
        if estimator_name == context["title"]:
            tags = estimator_class.get_class_tags()

            capabilities = {
                key.split(":")[1]: value
                for key, value in tags.items()
                if key.startswith("capability:")
            }

            html_output = """
            <div class="table-wrapper docutils container" id="id3">
            <table class="docutils align-default" id="id3">
            <caption>
            <span class="caption-text">Capabilities</span>
            <a class="headerlink" href="#id3" title="Link to this table">¶</a>
            </caption>
            <tbody>
            """

            for idx, (key, value) in enumerate(capabilities.items()):
                row_class = "row-odd" if idx % 2 == 0 else "row-even"
                formatted_key = key.replace("_", " ").title()
                if value is True:
                    formatted_value = "Yes"
                elif value is False:
                    formatted_value = "No"
                elif value is None:
                    formatted_value = "Not Set"
                else:
                    formatted_value = str(value)

                html_output += f"""
            <tr class="{row_class}">
                <th class="stub"><p>{formatted_key}</p></th>
                <td><p>{formatted_value}</p></td>
            </tr>
            """

            html_output += """
            </tbody>
            </table>
            </div>
            """

            html_content = context["body"]

            # Function to insert table into HTML content
            # Look for existing NOTES section outside methods
            start_methods = html_content.find('<dl class="py method">')
            section_before_methods = html_content[:start_methods]

            # Look for Notes section
            notes_heading = '<p class="rubric">Notes</p>'
            notes_pos = section_before_methods.find(notes_heading)

            if notes_pos != -1:
                # Notes exists, insert table after it
                insert_pos = notes_pos + len(notes_heading)
                context["body"] = (
                    html_content[:insert_pos]
                    + "\n"
                    + html_output
                    + html_content[insert_pos:]
                )
            else:
                # Need to create Notes section
                # Find position before References or Examples or Methods
                # whichever comes first
                ref_pos = section_before_methods.find(
                    '<p class="rubric">References</p>'
                )
                ex_pos = section_before_methods.find('<p class="rubric">Examples</p>')

                positions = [
                    pos for pos in [ref_pos, ex_pos, start_methods] if pos != -1
                ]
                insert_pos = min(positions) if positions else start_methods

                new_section = f'\n<p class="rubric">Notes</p>\n{html_output}\n'
                context["body"] = (
                    html_content[:insert_pos] + new_section + html_content[insert_pos:]
                )


def _add_page_assets(app, pagename, templatename, context, doctree):
    """Add the stylesheets and scripts only some of the pages need to those pages."""
    if pagename == "index":
        app.add_css_file("css/landing.css")
        app.add_js_file("js/landing.js", loading_method="defer")
    # filter box of the module pages of the API reference
    elif pagename.startswith("api_reference/") and "auto_generated" not in pagename:
        app.add_js_file("js/api_filter.js", loading_method="defer")


class _ModuleAutosummary(Autosummary):
    """Autosummary directive without signatures in the API reference module pages.

    The truncated signatures add noise to the long tables of the module pages. These
    tables are the ones with a toctree. The method tables numpydoc generates in the
    class pages have no toctree and keep their signatures.
    """

    def run(self):
        """Run the directive."""
        if "toctree" in self.options:
            self.options["nosignatures"] = None
        return super().run()


def setup(app):
    """Set up sphinx builder.

    Parameters
    ----------
    app : Sphinx application object
    """
    app.add_directive("autosummary", _ModuleAutosummary, override=True)
    app.connect("builder-inited", _make_estimator_overview)
    app.connect("html-page-context", _add_estimator_capabilities_table)
    app.connect("html-page-context", _add_page_assets)
