# Credit to https://stackoverflow.com/a/61574295

name: main auto-sync

on:
  schedule:
    - cron:  '30 0,12 * * *'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Merge upstream
        run: |
          git config --global user.name 'MatthewMiddlehurst'
          git config --global user.email 'MatthewMiddlehurst@users.noreply.github.com'

          git pull --unshallow

          git remote add upstream https://github.com/aeon-toolkit/aeon.git
          git fetch upstream

          git checkout main
          git merge --no-edit upstream/main

          git push origin main
