name: Dependabot Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/dependabot.yml'
      - '.github/workflows/check_dependabot.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: marocchino/validate-dependabot@v2
        id: validate

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.PR_APP_ID }}
          private-key: ${{ secrets.PR_APP_KEY }}

      - uses: thollander/actions-comment-pull-request@v2
        if: always()
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          message: ${{ steps.validate.outputs.markdown }}
