name: PR pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: tj-actions/changed-files@v35.9.0
        id: changed-files

      - name: List changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --files ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Check for missing init files
        run: build_tools/fail_on_missing_init_files.sh
        shell: bash
