name: PR pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "aeon/**"
      - ".github/workflows/**"
      - "pyproject.toml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test-nosoftdeps:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: "3.10"

      - name: Cache pip
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-3.10-${{ hashFiles('pyproject.toml') }}-nosoftdep


      - name: Install aeon and dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install .[dev]

      - name: Show dependencies
        run: pip list

#      - name: Run tests
#        run: |
#          python -m pytest -k 'test_all_estimators' --pyargs aeon.registry
#          python -m pytest -k 'test_check_estimator_does_not_raise' --pyargs aeon.utils
#          python -m pytest --pyargs aeon.tests.test_softdeps
#
  test-nosoftdeps-full:
    needs: test-nosoftdeps
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache pip
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-3.10-${{ hashFiles('pyproject.toml') }}-nosoftdep

      - name: Install aeon and dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install .[dev]

      - name: Show dependencies
        run: pip list

#      - name: Run tests
#        run: python -m pytest -k 'not TestAll' --ignore=aeon/utils/tests/test_mlflow_aeon_model_export.py --prtesting ${{ github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'full pytest actions') }}

  pytest:
    needs: test-nosoftdeps
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, macOS-12, windows-2022 ]
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up pip cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/Library/Caches/pip  # For macOS
            ~/.cache/pip          # For Linux
            ~\AppData\Local\pip\Cache # For Windows
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}

      - name: Install aeon and dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install .[all_extras,dev]

      - name: Show dependencies
        run: pip list

#      - name: Run tests
#        run: python -m pytest --prtesting ${{ github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'full pytest actions') }}

  codecov:
    if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'codecov actions') }}

    needs: test-nosoftdeps
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache pip
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-3.10-${{ hashFiles('pyproject.toml') }}-codecov

      - name: Disable Numba JIT
        run: echo "NUMBA_DISABLE_JIT=1" >> $GITHUB_ENV

      - name: Install aeon and dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install .[all_extras,unstable_extras,dev]

      - name: Show dependencies
        run: pip list

#      - name: Run tests
#        run: python -m pytest --cov=aeon --cov-report=xml

      - uses: codecov/codecov-action@v3
