name: Install and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: " "

      - name: List changed files
        run: echo '${{ steps.file_changes.outputs.files}}'

      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --files ${{ steps.file_changes.outputs.files }}

      - name: Check for missing init files
        run: build_tools/fail_on_missing_init_files.sh
        shell: bash

  run-notebook-examples:
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[all_extras,binder,dev]

      - name: Run example notebooks
        run: build_tools/run_examples.sh
        shell: bash

  test-nosoftdeps:
    needs: code-quality
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install aeon and dependencies
        run: python -m pip install .[dev]

      - name: Show dependencies
        run: python -m pip list

      - name: Run tests
        run: make PYTESTOPTIONS="--cov --cov-report=xml --timeout=600" test_softdeps

  test-nosoftdeps-full:
    needs: test-nosoftdeps
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install aeon and dependencies
        run: python -m pip install .[dev]

      - name: Show dependencies
        run: python -m pip list

      - name: Run tests
        run: make PYTESTOPTIONS="--cov --cov-report=xml --timeout=600" test_softdeps_full

  pytest:
    needs: test-nosoftdeps
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        python-version: [ '3.8', '3.9', '3.10' ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: python -m pip install .[dev,deep_learning]

      - name: Tests
        run: python -m pytest


  codecov:
    needs: test-nosoftdeps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Disable Numba JIT
        run: echo "NUMBA_DISABLE_JIT=1" >> $GITHUB_ENV

      - name: Install
        run: python -m pip install .[dev,deep_learning]

      - name: Tests
        run: python -m pytest --cov=tsml_eval --cov-report=xml

      - uses: codecov/codecov-action@v3
