name: Release

on:
  release:
    types:
      - published

jobs:
  check_manifest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: check-manifest --hook-stage manual

  build_project:
    needs: check_manifest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build project
        run: |
          python -m pip install build
          python -m build

      - name: Store build files
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*

  test_wheels:
    needs: build_project
    name: Test wheels on ${{ matrix.os }} with ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        python-version: [ '3.8', '3.9', '3.10' ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - if: matrix.os == 'windows-latest'
        name: Windows wheel filename
        run: echo "WHEELNAME=$(ls ./dist/aeon-*-none-any.whl)" >> $env:GITHUB_ENV
      - if: matrix.os != 'windows-latest'
        name: Unix wheel filename
        run: echo "WHEELNAME=$(ls ./dist/aeon-*-none-any.whl)" >> $GITHUB_ENV

      - if: matrix.os == 'windows-latest'
        name: Windows install
        run: python -m pip install "${env:WHEELNAME}[all_extras,dev]"
      - if: matrix.os != 'windows-latest'
        name: Unix install
        run: python -m pip install "${{ env.WHEELNAME }}[all_extras,dev]"

      - name: Tests
        run: python -m pytest

  upload_wheels:
    needs: test_wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
